// <auto-generated />
using System;
using LoveYourBudget.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoveYourBudget.DAL.Migrations
{
    [DbContext(typeof(LoveYourBudgetDbContext))]
    [Migration("20230109184851_AddBudgetConstraint")]
    partial class AddBudgetConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoveYourBudget.Budget", b =>
                {
                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Income")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Year", "Month");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("LoveYourBudget.BudgetRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BudgetId")
                        .HasColumnType("int");

                    b.Property<string>("BudgetMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BudgetYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BudgetYear", "BudgetMonth");

                    b.ToTable("BudgetRow");
                });

            modelBuilder.Entity("LoveYourBudget.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6772),
                            Name = "Groceries",
                            UpdatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6775)
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6781),
                            Name = "Phone",
                            UpdatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6783)
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6787),
                            Name = "Electricity",
                            UpdatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6789)
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6793),
                            Name = "Gas",
                            UpdatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6795)
                        },
                        new
                        {
                            Id = 5,
                            CreatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6799),
                            Name = "Broadband",
                            UpdatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6801)
                        },
                        new
                        {
                            Id = 6,
                            CreatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6805),
                            Name = "Streaming",
                            UpdatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6807)
                        },
                        new
                        {
                            Id = 7,
                            CreatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6811),
                            Name = "Transportation",
                            UpdatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6813)
                        },
                        new
                        {
                            Id = 8,
                            CreatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6817),
                            Name = "Restaurants",
                            UpdatedTime = new DateTime(2023, 1, 9, 19, 48, 50, 964, DateTimeKind.Local).AddTicks(6819)
                        });
                });

            modelBuilder.Entity("LoveYourBudget.ExpenseRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ExpenseRows");
                });

            modelBuilder.Entity("LoveYourBudget.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("LockInPeriod")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mortgage")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LoveYourBudget.BudgetRow", b =>
                {
                    b.HasOne("LoveYourBudget.Category", "Category")
                        .WithMany("BudgetRows")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoveYourBudget.Budget", "Budget")
                        .WithMany("BudgetRows")
                        .HasForeignKey("BudgetYear", "BudgetMonth")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LoveYourBudget.ExpenseRow", b =>
                {
                    b.HasOne("LoveYourBudget.Category", "Category")
                        .WithMany("ExpenseRows")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LoveYourBudget.Budget", b =>
                {
                    b.Navigation("BudgetRows");
                });

            modelBuilder.Entity("LoveYourBudget.Category", b =>
                {
                    b.Navigation("BudgetRows");

                    b.Navigation("ExpenseRows");
                });
#pragma warning restore 612, 618
        }
    }
}
